name = "Gaylord"
author = "Memelord"
version = "Versionlord"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "12990467536792982dab78a49dc853fa8d9a2c145e18f359f52822bad103f0ac"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
